# Site settings
title: Riffomonas
developer: Pat Schloss
email: pschloss@umich.edu
description: A project dedicated to improving the reproducibility of microbiome analyses
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://riffomonas.org" # the base hostname & protocol for your site
twitter_username: patschloss
github_username:  riffomonas

# Build settings
markdown: kramdown
